# site settings
title: Brendan Hu
subtitle: ""
headerIndexText: 'Home'
email: contact@brendanhu.com
description: ""
baseurl: ""
url: ""
author:
street_address: null
city: San Diego
state: CA
zip_code:
country:
phone: (510) 423-3241

# social settings
github_url: https://www.github.com/mithridatize
linkedin_url: https://www.linkedin.com/in/brendanhu
instagram_url: https://instagram.com/mithridatize
twitter_url: https://twitter.com/mithridatize

# build settings
markdown: kramdown

sass:
  style: compressed
